# To draw a ludo board

import turtle as bot
import math

step = 40
hypotenuse = 3*step
angle = 90
side = hypotenuse/math.sqrt(2)
bot.speed(35)
bot.left(45)
bot.width(3)
#drawing the yellow triangle
bot.fillcolor('yellow')
bot.begin_fill()
bot.forward(side)
bot.left(angle + 45)
bot.forward(hypotenuse)
bot.left(45 + angle)
bot.forward(side)
bot.left(angle)
bot.end_fill()

#drawing the green triangle
bot.right(90)
bot.fillcolor('green')
bot.begin_fill()
bot.forward(side)
bot.left(angle + 45)
bot.forward(hypotenuse)
bot.left(45 + angle)
bot.forward(side)
bot.left(angle)
bot.end_fill()

#drawing the red triangle
bot.right(90)
bot.fillcolor('red')
bot.begin_fill()
bot.forward(side)
bot.left(angle + 45)
bot.forward(hypotenuse)
bot.left(45 + angle)
bot.forward(side)
bot.left(angle)
bot.end_fill()

#drawing the blue triangle
bot.right(90)
bot.fillcolor('cyan')
bot.begin_fill()
bot.forward(side)
bot.left(angle + 45)
bot.forward(hypotenuse)
bot.left(45 + angle)
bot.forward(side)
bot.left(angle)
bot.end_fill()

#moving to the next position
bot.forward(side)
bot.left(45)

#drawing the four white sqaures in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the blue square in the first row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.end_fill()
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the last white sqauare in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing the 5 blue squares in the second row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.end_fill()

#drawing the white square in the second row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing all the white sqaures in the third row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#Going to the next position
bot.penup()
bot.right(angle)
bot.forward(step*2)
bot.pendown()

#Drawing the big blue sqaure
bot.begin_fill()
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(90)
bot.forward(step)
bot.left(90)
bot.forward(step)
bot.pendown()

#Drawing the white square inside the big blue sqaure
bot.fillcolor('white')
bot.begin_fill()
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.forward(step/2)
bot.right(angle)
bot.forward(step/2)
bot.left(angle)
bot.pendown()

#Drawing the 4 small blue squares inside the white square
bot.fillcolor('cyan')
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.right(angle)
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.left(angle)
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.right(angle*2)
bot.forward(step*2)
bot.right(angle*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(angle*2)
bot.forward(step*3/2)
bot.left(angle)
bot.forward(step*11/2)
bot.left(angle)

bot.fillcolor('yellow')

#drawing the four white sqaures in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the yellow square in the first row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.end_fill()
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the last white sqauare in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing the 5 yellow squares in the second row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.end_fill()

#drawing the white square in the second row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing all the white sqaures in the third row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#Going to the next position
bot.penup()
bot.right(angle)
bot.forward(step*2)
bot.pendown()

#Drawing the big yellow sqaure
bot.begin_fill()
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(90)
bot.forward(step)
bot.left(90)
bot.forward(step)
bot.pendown()

#Drawing the white square inside the big yellow sqaure
bot.fillcolor('white')
bot.begin_fill()
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.forward(step/2)
bot.right(angle)
bot.forward(step/2)
bot.left(angle)
bot.pendown()

#Drawing the 4 small yellow squares inside the white square
bot.fillcolor('yellow')
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.right(angle)
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.left(angle)
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.right(angle*2)
bot.forward(step*2)
bot.right(angle*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(angle*2)
bot.forward(step*3/2)
bot.left(angle)
bot.forward(step*11/2)
bot.left(angle)

bot.fillcolor('green')

#drawing the four white sqaures in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the green square in the first row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.end_fill()
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the last white sqauare in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing the 5 green squares in the second row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.end_fill()

#drawing the white square in the second row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing all the white sqaures in the third row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#Going to the next position
bot.penup()
bot.right(angle)
bot.forward(step*2)
bot.pendown()

#Drawing the big green sqaure
bot.begin_fill()
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(90)
bot.forward(step)
bot.left(90)
bot.forward(step)
bot.pendown()

#Drawing the white square inside the big blue sqaure
bot.fillcolor('white')
bot.begin_fill()
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.forward(step/2)
bot.right(angle)
bot.forward(step/2)
bot.left(angle)
bot.pendown()

#Drawing the 4 small green squares inside the white square
bot.fillcolor('green')
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.right(angle)
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.left(angle)
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.right(angle*2)
bot.forward(step*2)
bot.right(angle*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(angle*2)
bot.forward(step*3/2)
bot.left(angle)
bot.forward(step*11/2)
bot.left(angle)

bot.fillcolor('red')

#drawing the four white sqaures in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the red square in the first row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.end_fill()
bot.penup()
bot.forward(step)
bot.pendown()

#drawing the last white sqauare in the first row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing the 5 red squares in the second row
bot.begin_fill()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.end_fill()

#drawing the white square in the second row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)

#Going to the next row
bot.penup()
bot.backward(step*5)
bot.left(angle)
bot.forward(step)
bot.right(angle)
bot.pendown()

#Drawing all the white sqaures in the third row
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.forward(step)
bot.left(angle)
bot.penup()
bot.forward(step)
bot.pendown()

#Going to the next position
bot.penup()
bot.right(angle)
bot.forward(step*2)
bot.pendown()

#Drawing the big red sqaure
bot.begin_fill()
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.forward(step*6)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(90)
bot.forward(step)
bot.left(90)
bot.forward(step)
bot.pendown()

#Drawing the white square inside the big blue sqaure
bot.fillcolor('white')
bot.begin_fill()
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.forward(step*4)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.forward(step/2)
bot.right(angle)
bot.forward(step/2)
bot.left(angle)
bot.pendown()

#Drawing the 4 small red squares inside the white square
bot.fillcolor('red')
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.right(angle)
bot.penup()
bot.forward(step*2)
bot.pendown()
bot.left(angle)
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()
bot.penup()
bot.right(angle*2)
bot.forward(step*2)
bot.right(angle*2)
bot.pendown()
bot.begin_fill()
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.forward(step)
bot.right(angle)
bot.end_fill()

#Going to the next position
bot.penup()
bot.right(angle*2)
bot.forward(step*3/2)
bot.left(angle)
bot.forward(step*11/2)
bot.right(angle*3/2)
bot.forward(side)

